# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.box = "centos/7"
   
   config.ssh.insert_key = false
   
   config.vm.synced_folder ".","/vagrant", disabled: true

   config.vm.provider:virtualbox do |v|
    v.memory = 6144
    v.cpus = 2
    v.linked_clone = true
   end

   config.vm.define "tower" do |tower|
    tower.vm.hostname = "tower.test"
    tower.vm.network:private_network, ip:"192.168.1.70"
   end

end
